<?php
define('MODULO_DEFECTO','home');
define('LAYOUT_DEFECTO','inicio.php');//admin
define('LAYOUT_LOGIN','login.php');//admin
define('LAYOUT_INICIO','inicio.php');//Para cualquier tipo de usuario
define('LAYOUT_EMPLEADO','empleado.php');//Para  empleado
define('LAYOUT_CLIENTE','cliente.php');//Para  empleado
define('LAYOUT_ADMIN','admin.php');//Para  empleado
define('MODULO_PATH',realpath('paginas'));
define('LAYOUT_PATH',realpath('plantillas'));

$conf['404']=array(
'archivo'=>'404.php',
'layout'=>LAYOUT_INICIO
);
$conf['home']=array(
'archivo'=>'home.php',
'layout'=>LAYOUT_INICIO
);
$conf['historia']=array(
'archivo'=>'historia.php',
'layout'=>LAYOUT_INICIO
);
$conf['servicios']=array(
'archivo'=>'servicios.php',
'layout'=>LAYOUT_INICIO
);
$conf['sucursales']=array(
'archivo'=>'sucursales.php',
'layout'=>LAYOUT_INICIO
);
$conf['autenticar']=array(
'archivo'=>'autenticar.php',
'layout'=>LAYOUT_INICIO
);
$conf['logout']=array(
'archivo'=>'logout.php',
'layout'=>LAYOUT_INICIO
);
$conf['login']=array(
'archivo'=>'login.php',
'layout'=>LAYOUT_INICIO
);
$conf['contact']=array(
'archivo'=>'contactenos.php',
'layout'=>LAYOUT_INICIO
);
$conf['cambiarcontrasena']=array(
'archivo'=>'frmCambiarContra.php',
'layout'=>LAYOUT_INICIO
);
//admin
$conf['imprimirreserva']=array(
'archivo'=>'imprimirreserva.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['asignarhorario']=array(
'archivo'=>'admin/frmAsignarhorario.php',
'layout'=>LAYOUT_INICIO
);
$conf['usuarioempleado']=array(
'archivo'=>'admin/usuarioempleado.php',
'layout'=>LAYOUT_ADMIN
);
$conf['registroempleado']=array(
'archivo'=>'admin/registroempleados.php',
'layout'=>LAYOUT_ADMIN
);
$conf['buscarempleado']=array(
'archivo'=>'admin/buscarempleado.php',
'layout'=>LAYOUT_ADMIN
);
$conf['actualizarempleado']=array(
'archivo'=>'admin/actualizarempleado.php',
'layout'=>LAYOUT_ADMIN
);
$conf['registraroferta']=array(
'archivo'=>'admin/registrooferta.php',
'layout'=>LAYOUT_ADMIN
);
$conf['registroimagenes']=array(
'archivo'=>'admin/registroimagenes.php',
'layout'=>LAYOUT_ADMIN
);
$conf['buscarreporteventa']=array(
'archivo'=>'admin/buscarreporteventa.php',
'layout'=>LAYOUT_ADMIN
);
$conf['registrarservicios']=array(
'archivo'=>'admin/frmRegistrarServicio.php',
'layout'=>LAYOUT_ADMIN
);
$conf['buscarservicio']=array(
'archivo'=>'admin/buscarservicio.php',
'layout'=>LAYOUT_ADMIN
);
$conf['actualizarservicio']=array(
'archivo'=>'admin/frmActualizarServicio.php',
'layout'=>LAYOUT_ADMIN
);
$conf['registrartemporada']=array(
'archivo'=>'admin/frmRegistroTemporada.php',
'layout'=>LAYOUT_ADMIN
);
$conf['registroproducto']=array(
'archivo'=>'admin/pruebaregistro.php',
'layout'=>LAYOUT_ADMIN
);
$conf['consultaempleado']=array(
'archivo'=>'admin/actualizarempleado.php',
'layout'=>LAYOUT_ADMIN
);
$conf['enviarCorreo']=array(
'archivo'=>'enviarCorreo.php',
'layout'=>LAYOUT_ADMIN
);
$conf['validarcorreo']=array(
'archivo'=>'validarcorreo.php',
'layout'=>LAYOUT_INICIO
);
$conf['actualizarreserva']=array(
'archivo'=>'empleado/ActualizarReserva.php',
'layout'=>LAYOUT_EMPLEADO
);

$conf['log']=array(
'archivo'=>'admin/log.php',
'layout'=>LAYOUT_ADMIN
);
$conf['nuevasucursal']=array(
'archivo'=>'admin/frmRegistroSucursal.php',
'layout'=>LAYOUT_ADMIN
);
$conf['registrocargo']=array(
'archivo'=>'admin/frmRegistroCargo.php',
'layout'=>LAYOUT_ADMIN
);

//CLIENTE
$conf['iniciarreserva']=array(
'archivo'=>'cliente/frmIniciarReserva.php',
'layout'=>LAYOUT_CLIENTE
);
$conf['vistareserva']=array(
'archivo'=>'cliente/vistareserva.php',
'layout'=>LAYOUT_CLIENTE
);
$conf['reprogramarreserva']=array(
'archivo'=>'cliente/frmReprogramarReserva.php',
'layout'=>LAYOUT_CLIENTE
);
$conf['registrarse']=array(
'archivo'=>'cliente/frmRegistroCliente.php',
'layout'=>LAYOUT_INICIO
);
$conf['imprimirreservac']=array(
'archivo'=>'imprimirreserva.php',
'layout'=>LAYOUT_CLIENTE
);
//EMPLEADO
$conf['usuariocliente']=array(
'archivo'=>'empleado/crearUsuario.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['hojamateriales']=array(
'archivo'=>'empleado/frmHojaMateriales.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['pedidos']=array(
'archivo'=>'empleado/frmPedidos.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['registrarcliente']=array(
'archivo'=>'empleado/frmRegistroCliente.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['reservarservicio']=array(
'archivo'=>'empleado/frmIniciarReserva.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['vistareservaemp']=array(
'archivo'=>'empleado/frmVistaReservaEmpleado.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['buscarcliente']=array(
'archivo'=>'empleado/frmBuscarCliente.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['modificarcliente']=array(
'archivo'=>'empleado/frmModificarCliente.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['reporteventas']=array(
'archivo'=>'empleado/frmReporteVenta2.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['ingresoproductos']=array(
'archivo'=>'empleado/frmIngresoProductos.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['salidaproductos']=array(
'archivo'=>'empleado/frmSalidaProductos.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['entregamateriales']=array(
'archivo'=>'empleado/frmEntregaMateriales.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['buscaremp']=array(
'archivo'=>'empleado/frmBuscarEmpleado.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['factura']=array(
'archivo'=>'empleado/frmFactura.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['inventario']=array(
'archivo'=>'empleado/inventario.php',
'layout'=>LAYOUT_EMPLEADO
);
$conf['expediente']=array(
'archivo'=>'empleado/frmExpediente.php',
'layout'=>LAYOUT_INICIO
);

?>
